### ISSUE TITLE
Put a holding message in empty pages?

### ISSUE THREAD

**Issue by martin-nc** [elixir-europe/infectious-diseases-toolkit#104]
I notice there are a lot of empty pages. That makes me think of the old customer service cliché, "Always exceed customer expectations." If we promise content and make people click for it, then perhaps we need to fulfil that promise. This seems particularly cruel on landing pages (e.g. https://www.infectious-diseases-toolkit.org/pathogen_characterisation/), where we know there is no content behind the tiles, but we don't warn people before they click. 

It's true there is the "Site under construction" message on the home page, but it's not clear how far the site is "complete". I guess all the links suggested to me I could click on them and find something. If there is no content, and we want the empty pages to be live, perhaps we could at least give people information on those pages about why the content is not there. We could just repeat the box on the home page, but this also seems like a an opportunity to engage people. 

Is there a rough editorial timetable that we could link to, showing when different pages should be completed? Could the Twitter link be put there, if updates are announced on Twitter? If we can't/don't want to announce updates on Twitter, what about an RSS feed or a link to visualping (https://visualping.io/) so people can see when content is added? There are also [browser addons](https://chrome.google.com/webstore/detail/distill-web-monitor/inlikjemeeknofckkjolnjbpehgadgge?hl=en) that might be useful for people. It seems a shame to present people with a white wall! Just a thought, anyway.

**Comment by rabuono** [comment]
Showing a message on the empty pages sounds like a rather good idea. With the text, we could add a link tot he [contribute pages](https://www.infectious-diseases-toolkit.org/contribute/).
If a page is already being worked on, we could also link to the corresponding issue.
Does this sound reasonable?

**Comment by hedi-ee** [comment]
Add also a link to the https://www.infectious-diseases-toolkit.org/about/news page

**Comment by hedi-ee** [comment]
"The content of this page is currently missing because we have not had a chance to create it yet.
All the content of the IDTkit is created by volunteers and overseen by an editorial board. If you feel you could contribute to this or another page, we welcome you with open hearts. Various ways to contribute to IDTkit are captured at https://www.infectious-diseases-toolkit.org/contribute/. New content is announced as a news item and shown on the front page.  All the news can be seen at https://www.infectious-diseases-toolkit.org/about/news. If you wish to follow the updates, we suggest setting up a [Visualping](https://visualping.io/) to the page"

**Comment by martin-nc** [comment]
What about:

> **We are still working on the content for this page.** If you are interested in adding to the page then please **[feel free to contribute](https://www.infectious-diseases-toolkit.org/contribute/)**. This is a community-driven website, so contributions are welcome! You will, of course, be listed as a contributor on the page.
> 
> New content is announced on the [home page]( https://www.infectious-diseases-toolkit.org/) and [news page]( https://www.infectious-diseases-toolkit.org/about/news), so please check for updates there. You can also watch for changes on this page by using a free service like [Visual Ping](https://visualping.io/) or [Distill Web Monitor](https://distill.io/), or by using a [browser add-on](https://chrome.google.com/webstore/detail/distill-web-monitor/inlikjemeeknofckkjolnjbpehgadgge?hl=en).

or add a button to the first paragraph:

> **We are still working on the content for this page.** If you are interested in adding to the page, then: 
> 
> <a href="https://www.infectious-diseases-toolkit.org/contribute">![Screenshot 2022-12-01 at 17 16 10](https://user-images.githubusercontent.com/15261745/205117562-8ae478f1-a821-44b0-9ac0-0b31b58b00c8.png)</a>
> 
> This is a community-driven website, so contributions are welcome! You will, of course, be listed as a contributor on the page.

**Comment by bedroesb** [comment]
I like it, let me create a snippet!

**Comment by ppalagi** [comment]
Me too, I like both. The snippet is a great idea!

**Comment by bedroesb** [comment]
![Screenshot from 2022-12-05 12-07-15](https://user-images.githubusercontent.com/44875756/205622703-2c8d91e2-33e1-4295-a94f-3a3493aaa645.png)

**Comment by bedroesb** [comment]
If you like this, than here is the snippet: 

```
**We are still working on the content for this page.** If you are interested in adding to the page, then:

[Feel free to contribute](/contribute/){: class="btn btn-primary btn-lg rounded-pill"}

This is a community-driven website, so contributions are welcome! You will, of course, be listed as a contributor on the page.

New content is announced on the [home page](/) and [news page](/about/news), so please check for updates there. You can also watch for changes on this page by using a free service like [Visual Ping](https://visualping.io/) or [Distill Web Monitor](https://distill.io/), or by using a [browser add-on](https://chrome.google.com/webstore/detail/distill-web-monitor/inlikjemeeknofckkjolnjbpehgadgge?hl=en).
```
