### ISSUE TITLE
Socioeconomic data - Data sources

### ISSUE THREAD

**Issue by lauportell** [elixir-europe/infectious-diseases-toolkit#108]
**What topic do you wish to add?**
Socioeconomics data sources

**Resources**
https://docs.google.com/document/d/1GAljkcNYJqbJcrfvv7U00arj5seWpc2xYsuivltTy7Q/edit?usp=sharing

**Comment by bedroesb** [comment]
The section got renamed and is now located here: https://www.infectious-diseases-toolkit.org/socioeconomic-data/data-sources
