### ISSUE TITLE
Human clinical and health data - Data sources

### ISSUE THREAD

**Issue by lauportell** [elixir-europe/infectious-diseases-toolkit#109]
**What topic do you wish to add?**
Human clinical and health data sources

**Resources**
https://docs.google.com/document/d/1Hds3vxLINCjGaNBaIFqjW3ksJWcJv9sDDGKj6EC0f98/edit?usp=sharing

**Comment by IrisVanDam** [comment]
Hey Laura,
We have been struggling a little to understand what direction to go with the topics and the subheadings. Should this be like an example? Typical for human clinical and health data sources are the more complex issues related to data availability and data access. Would it make sense to turn these into two topics and under considerations explain why we need to consider these issues? 
On another note we were also wondering, could it make sense to move the subheading 'Standards, schemas, ontologies and vocabularies' to data description? 
Today I will try to elaborate the introduction section and the section on 'What is considered as human clinical and health data' a little further. Thanks for all your help so far!

**Comment by lauportell** [comment]
Hi Iris,
The topics and subheading can be anything that you think it is important to mention when working with human clinical and health data. Therefore, I think it is a good idea to mention the issues related to data availability and data access.
Here you can see how it is done in the RDMkit, and you can use it as guidance: https://rdmkit.elixir-europe.org/rare_disease_data
As for the standards, I think here you'd need to mention the specific standards the data sources you are mentioning in the page use. Not a long description, but to know what they are using. And then, this should be linked to the data description page for a further explanation. Would that make sense?
Thank you!

**Comment by IrisVanDam** [comment]
Hey Laura,
Thanks for this clear reply! And sorry for the delay in getting back to you from my side. We have decided to go with the topics 'Finding data sources' and 'Data access' as starters. Let's try them out with the new template and get back to you if we would get stuck along the way.

**Comment by M-casado** [comment]
The document was reviewed and could be added already, @IrisVanDam

**Comment by IrisVanDam** [comment]
Agreed @M-casado. As it have mainly been the two of us working this page, I had asked for another IDTk editor to review the current page on the Google Drive. However, I will just add what we have so far to GitHub and then we can move forward from there.
