### ISSUE TITLE
Adding a note for users of Ruby 3.x

### ISSUE THREAD

**Issue by martin-nc** [elixir-europe/infectious-diseases-toolkit#138]
**Link to the page of interest**
https://www.infectious-diseases-toolkit.org/contribute/working-with-git

**Describe what you would like to change on the page**
In the section "Run using Jekyll directly" , step 5 it says run `bundle exec jekyll serve`. If you're on Ruby 3.x I think you might run get an error like:

> bundler: failed to load command: jekyll (/Users/cookm/.rbenv/versions/3.1.3/bin/jekyll)
> /Users/cookm/.rbenv/versions/3.1.3/lib/ruby/gems/3.1.0/gems/jekyll-3.9.3/lib/jekyll/commands/serve/servlet.rb:3:in **`require': cannot load such file -- webrick (LoadError)**

See this issue: https://github.com/jekyll/jekyll/issues/8523. As noted in the issue, the solution is to add webrick: `bundle add webrick`. So maybe we should add that in point 5: "If this command returns an error, try running `bundle add webrick`' before trying `bundle exec jekyll serve` again (see [this issue](https://github.com/jekyll/jekyll/issues/8523))."  @bedroesb I guess this is the "compatibility issue" mentioned in the introduction to this section of the page? Or maybe there are more issues!

**Comment by bedroesb** [comment]
wohoow! Let's do that
