### ISSUE TITLE
Pathogen characterisation - Data description

### ISSUE THREAD

**Issue by LianeHughes** [elixir-europe/infectious-diseases-toolkit#151]
**Pathogen Characterisation - data description**
Need to finalise the pathogen characterisation data description page that was started at the IDTk contentathon.

**Are there existing pages in the Infectious Diseases Toolkit website related to the requested page?**
Initiation of new topic page

**Resources**
Use Google doc that in our BY-COVID folder (link not shared here).

**Comment by wna-se** [comment]
Looking forward to continue working on this.
