### ISSUE TITLE
Quality control - Human biomolecular data

### ISSUE THREAD

**Issue by lauportell** [elixir-europe/infectious-diseases-toolkit#158]
**What topic do you wish to add?**
New page human biomolecular data - Quality control

**Resources**
https://docs.google.com/document/d/1bsp4bmsC7dfzFzdzc3BtPX6ySREFYBRhjsVDg_4xV6Q/edit?usp=sharing

@ainajene

**Comment by lauportell** [comment]
@ainajene @solcos this page still has some comments in the google docs that need to be solved before we start a pull request to add the content in the IDTk

**Comment by bedroesb** [comment]
This is done!
