### ISSUE TITLE
Update description of the page (metadata)

### ISSUE THREAD

**Issue by bedroesb** [elixir-europe/infectious-diseases-toolkit#16]
One liner about the website

**Comment by bedroesb** [comment]
Line that needs to be changed: https://github.com/elixir-europe/infectious-diseases-toolkit/blob/main/_config.yml#L7

**Comment by hedi-ee** [comment]
What about "Best practices and showcase solutions to data challenges you can use for responding to infectious diseases outbreaks"

**Comment by martin-nc** [comment]
What about:

> Find tools and guidelines to help you utilise infectious disease data, and respond quickly to disease outbreaks.

or 

> Find tools and guidelines to help you access, analyse and share infectious disease data, and respond quickly to disease outbreaks.

**Comment by EvaGarciaAlvarez** [comment]
I’d merge both suggestions: “Best practices, tools and guidelines for infectious diseases data access, analysis and sharing, to enable quick responses to outbreaks”
