### ISSUE TITLE
National resources page for Norway

### ISSUE THREAD

**Issue by Nazeeefa** [elixir-europe/infectious-diseases-toolkit#160]
**What topic do you wish to add?**
National resources page for Norway (will close #146 )

**Comment by bedroesb** [comment]
this will close #146

**Comment by korbinib** [comment]
This is a great start. I made some suggestions here: [#21 ](https://github.com/ELIXIR-Belgium/infectious-diseases-toolkit-sandbox/pull/21)
The project section looks a bit random and will change quickly maybe one could link to [projektdatabanken](https://prosjektbanken.forskningsradet.no/) or [CRISTIN](https://app.cristin.no/search.jsf?type=project) instead to avoid dead links at the institutions?

**Comment by Nazeeefa** [comment]
Thanks! Regarding https://www.influensasenteret.no/about/, the about page suggests it's a national project that receives funding from university/hospital/NFR. We understood it as not an institution-level project.

**Comment by Nazeeefa** [comment]
Thanks @korbinib! Just want to mention that we did think about adding CAMRIA (Combatting Antimicrobial Resistance with Interdisciplinary Approaches) under 'institutional initiatives' but didn't because it involves multiple organisations and as we understood that the initiative is for multiple regions, not specific to one location.
