### ISSUE TITLE
New FAIRness page

### ISSUE THREAD

**Issue by M-casado** [elixir-europe/infectious-diseases-toolkit#163]
**What topic do you wish to add?**
FAIR principles applied to infectious diseases.

**Are there existing pages in the Infectious Diseases Toolkit website related to the requested page?**
No: it is a non-existing page, that would go under the merged HBD and HCHD.

**Resources**
* FAIRness Contentathon [google doc](https://docs.google.com/document/d/1m4dJKdazBurcb2n6yBPuv8_9lWOt1J73se4XkrvysYI/edit#)

**Context**
It is a request derived from the IDTk contentathon. The google document is not ready (reviewed, merged, etc.) to be added yet. Once I have finished it I will create a PR from my fork of the project adding it.

**Comment by IrisVanDam** [comment]
Last week or two weeks ago I was talking about the [FAIRness page](https://github.com/elixir-europe/infectious-diseases-toolkit/issues/163) with Romain. He suggested that, if it is decided to not keep this page within the IDTk we could turn this into a paper and publish it. The paper can then in turn be referenced throughout the IDTk, where necessary. 
@M-casado what do you think about this? Maybe this is an approach we could discuss during the next editors meeting?

**Comment by M-casado** [comment]
Hi @IrisVanDam, I would be happy to attend the discussion: could I join this one specifically? I don't have strong feelings on any of these alternatives. I wouldn't like to overextend it, and we should also check whether this has been published as is already. In any case I will ask my manager and colleagues and continue from there.

**Comment by M-casado** [comment]
Hi @IrisVanDam & @RomainDavid24, regarding the suggested paper, I feel that the best approach would be:
-  If **what we wrote for FAIRness is sufficiently useful for the IDTK**, we should **create a page** containing it within the IDTK. Does not matter necessarily where, or if a subgroup of another page. And other pages can reference it. 
- If, on the other hand, we deem this information to be **too generic, and not entirely necessary for the IDTK**, and we just need to reference FAIRness from within the IDTK but without it being a page on its own, I would advise to **reference other publications** that revolve around FAIR principles. 

The work that would be required to write a paper on this topic outweighs the benefits of referencing FAIR within the IDTK if not entirely linked to infectious diseases. I reckon that, when we started with the page, we were trying to be close to the original IDTK topic, but little by little when more pages needed to reference FAIRness, it grew outside of the main topic, and may be unnecessary to write a paper as it is now.

**Comment by IrisVanDam** [comment]
Hey Marcos and Romain,

Last week Shona brought this up during the IDTk editors meeting and it was decided to make a decision about this during the virtual contentathon in September (~ see previous mails from Martin and me).
Although it’s still a while, being able to talk this over all together with the both of you and the IDTk editors might be the easiest way forward.

Hope to see/hear you both soon!

Many regards,
Iris

**Comment by M-casado** [comment]
@IrisVanDam, I guess the 2 hour meeting in September is the contentathon you refer to. I already gave my availability in the ~pretty long~ form :)

**Comment by IrisVanDam** [comment]
@M-casado Haha, jup, that's the one :D! Thanks Marcos!

**Comment by bedroesb** [comment]
Because of the restructuring of the website that took place, we will quicker be able to decide were to place this page since we now allow the creation of non domain specific data type pages! To be continued
