### ISSUE TITLE
New "Human Clinical and Health Data - Data Sources" page

### ISSUE THREAD

**Issue by M-casado** [elixir-europe/infectious-diseases-toolkit#164]
**What topic do you wish to add?**
Content of the Human Clinical and Health Data - **Data Sources**.

**Are there existing pages in the Infectious Diseases Toolkit website related to the requested page?**
``hchd_data_sources``, but based on the merge between HCHD and HBD, it may change.

**Resources**
If there are resources that could be utilised for writing the new page, please list them below:
* HCHD sources [google doc](https://docs.google.com/document/d/1Hds3vxLINCjGaNBaIFqjW3ksJWcJv9sDDGKj6EC0f98/edit#)

**Context**
The document is yet to be finished, this issue is just a reminder for a future PR to the project.

**Comment by bedroesb** [comment]
Hello @M-casado , there is already an issue about the content of this pag here: #109. I will move the content you have added here to that issue!
