### ISSUE TITLE
Merge Human Biomolecular and Clinical data

### ISSUE THREAD

**Issue by M-casado** [elixir-europe/infectious-diseases-toolkit#165]
**What topic do you wish to add?**
Given the overlap, Human Biomolecular Data and Human Clinical and Health Data are to be merged.

**Are there existing pages in the Infectious Diseases Toolkit website related to the requested page?**
Possibly all starting by ``hchd_`` and ``hbd_``

**Resources**
Content from other sections and pages. Depends on other tickets:
* https://github.com/elixir-europe/infectious-diseases-toolkit/issues/163
* https://github.com/elixir-europe/infectious-diseases-toolkit/issues/164* 
* https://github.com/elixir-europe/infectious-diseases-toolkit/pull/155

**Comment by bedroesb** [comment]
Since the main topics have been changed to Data sources etc and not by data types, allowing the creation of general pages, this will be possible be default. See #263  Thanks for keeping track of this!
