### ISSUE TITLE
Define a style for page IDs

### ISSUE THREAD

**Issue by rabuono** [elixir-europe/infectious-diseases-toolkit#169]
On the Editorial board guide page at `/contribute/editorial-board-guide`

It can be helpful to define a style for the page IDs of new pages.
This will help to avoid unnecessary heterogeneity in the the page IDs of new pages.
The currently existing page IDs are in snake case, it might be easiest to keep with that for new page IDs

**Comment by bedroesb** [comment]
In last editorial meeting we decided to go for snake-case
