### ISSUE TITLE
Data analysis - Socioeconomic data

### ISSUE THREAD

**Issue by hedi-ee** [elixir-europe/infectious-diseases-toolkit#252]
The issue is about creating content for https://www.infectious-diseases-toolkit.org/socioeconomic-data/data-analysis using the Google Docs for editing.

We expect Simon Saldner to be the main driver and @diana-pilvar and @hedi-ee to be associated editors.

**Comment by bedroesb** [comment]
Work has been initiated on this topic in [Google Docs](https://docs.google.com/document/d/1WMTYyeh1MgkqcT1IlKnZsy5sgap5KyN02fYW2qM771o/edit)
