### ISSUE TITLE
Ethical, legal, and social issues - Socioeconomic data

### ISSUE THREAD

**Issue by LianeHughes** [elixir-europe/infectious-diseases-toolkit#254]
**What topic do you wish to add?**

Adding at least the initial content of theethical, legal, and social issues page.

**Context**
We hope to be able to add this content in the contentathon in January . EKKE set to create content

**Comment by bedroesb** [comment]
@LianeHughes Do I remember correctly that we replaced this by having only a general ELSI page, the one that is live now? So we can close this issue?

**Comment by LianeHughes** [comment]
you are completely correct
