### ISSUE TITLE
Data analysis - Pathogen characterisation

### ISSUE THREAD

**Issue by bedroesb** [elixir-europe/infectious-diseases-toolkit#285]
Topics:

- Metadata harmonisation (T2.5) for later analysis / integration
- What metadata the pipeline accepts
- Genomics
- Register workflows/scripts + identifiers + tags in WFhub + refer ID
- Proteomics
- Imaging
- Pathways
- Policy assessment

**Comment by bedroesb** [comment]
Work has been initiated on [Google Docs](https://docs.google.com/document/d/1WvPV9huoWxoMNEDZczxaO9EA_v10BqILF_A2MNaTCfE/edit)

**Comment by Aryanujan01729** [comment]
Is there something i can contribute in this project....
