### ISSUE TITLE
Test the structure with content from the Nordic Pandemic Infrastructure (NeIC PaRI) project’s guide

### ISSUE THREAD

**Issue by wna-se** [elixir-europe/infectious-diseases-toolkit#32]
Over the next few weeks I will try to identify relevant content from the PaRI project that could be used to inspire content for some of the sections.

- [ ] [Project summary slides](https://docs.google.com/presentation/d/18g3wIjIECQDvslu1o348qia-7d7xQXRnvCvtT328u_U/edit)
- [ ] [Partners’ guide to SARS-CoV-2 genome data sharing](https://docs.google.com/document/d/1X1_JOvjryb0je-sC4NkYL12-DWaan8QYXEb1EdTHhZE/edit)
- [ ] [Schematic overview of research documentation and data outputs](https://github.com/elixir-europe/infectious-diseases-toolkit/assets/1221165/d737cee2-aa52-4f73-b143-0353d9196882)
- [ ] [PaRI Data Dictionaries and Data Mappings](https://docs.google.com/spreadsheets/d/1gNpdZKOUKPemMUHR107JRSeaWjPczlMIUp5fP5-kR9g/edit#gid=1524315810)
- [ ] [PaRI Galaxy, data flows, etc.](https://docs.google.com/presentation/d/1WqVmLs_9hNDc1hhXN5qeMtbLSz75zkzsIYACohGnH0Q/edit#slide=id.gffa010e463_0_487)

**Comment by bedroesb** [comment]
@wna-se  based on the closed pull request, do you think this issue can be closed?

**Comment by bedroesb** [comment]
This is done.
