### ISSUE TITLE
Update Beacon information in sensitive data

### ISSUE THREAD

**Issue by ainajene** [elixir-europe/infectious-diseases-toolkit#320]
**Link to the page of interest**
https://www.infectious-diseases-toolkit.org/data-sources/human-biomolecular-data
https://www.infectious-diseases-toolkit.org/data-sources/human-clinical-and-health-data

**Describe what you would like to change on the page**
I'd like to update information related to Beacon v2 as well as add the list of Beacons with COVID-19 data in production (work accomplished by D2.3 in by-covid)

**List the tool(s)or resource(s) that are missing on the page (if applicable)**
- Name
- Link
- Description
- Registry (biotools or/and FAIRsharing ID) (optional)

**Comment by bedroesb** [comment]
@ainajene Hello again! ;) This is very much welcomed. Would you want to update the tool information itself, or the text/content surrounding the tool? 

Both are possible through a pull request.
- Updating the tool can be done by editing this file: https://github.com/elixir-europe/infectious-diseases-toolkit/blob/main/_data/tool_and_resource_list.yml
- Updating the content around the tool of the pages you mention can be done by clicking the pencil icon next to the title

The editorial team will from there onwards be happy to review you pull request.

**Comment by ainajene** [comment]
Hello! I've created a pull requests ([PR 322](https://github.com/elixir-europe/infectious-diseases-toolkit/pull/322)). So far, I've only updated the bio-molecular page. Although some information also affect the clinical and health data page. But the information is exactly the same, and not sure we want to duplicate content. 

Also, do you think that I should add each beacon as a tool in the tool and resource list?

**Comment by bedroesb** [comment]
Hello @ainajene we decided in our last editorial meeting that we would not replicate the exact same block we added to the biomolecular page. This also means that we will close this pull request. Thanks a lot for your contribution!
