### ISSUE TITLE
Headings instructions in the style guide is duplicated

### ISSUE THREAD

**Issue by lidix91** [elixir-europe/infectious-diseases-toolkit#47]
In the Text section, there are instructions for "Headings" and "Titles", both includes information about capitalisation, in Titles mentions acronyms. 

https://www.infectious-diseases-toolkit.org/contribute/style_guide

**Comment by rabuono** [comment]
Thanks for pointing it out @lidix91 !

I have added a Titles exception to the Acronym entry:
`Acronyms: spell them out the first time they appear on a page, except for Titles.`

Included in this PR #53 
Does it solve the issue?

**Comment by lidix91** [comment]
I checked the current version and I realised that the issue has not been solved. We still have duplication:

Headings:
* Only the first word is capitalised, unless other words are proper nouns.

Titles: only the first word and acronyms are capitalised.

I understand that "Headings" and "Titles" are the same, maybe both concepts are referring to different situations. In my opinion, the last "Titles: only the first ..." should be removed.

**Comment by martin-nc** [comment]
I think "title" is referring to what is in the HTML `<title>` tag. This is taken from the "title" variable in the front matter of each page e.g.:

```
---
title: National resources
---
```

The title is not visible in the page, but in the browser tab, search engine results, bookmarks etc. It's not clear from the text, though. So it's not the same as "Headings".  I think we should make this explicit. So we could say something like:

> Titles (the "title" in the front matter of pages): only the first word and acronyms are capitalised.

**Comment by lidix91** [comment]
better!
