### ISSUE TITLE
Overview link in Tools and resource list spreadsheet leads to RDMkit

### ISSUE THREAD

**Issue by rabuono** [elixir-europe/infectious-diseases-toolkit#48]
In cell B1 there is a link to `overview` that leads to RDMkit
It should lead to the corresponding page in IDTk
The corresponding page in IDTk is not available yet.
[Spreadsheet link here](https://docs.google.com/spreadsheets/d/13tqfSbgivokfEkxGXPRFShVhCmO4VuTQRe4uQgJOMbc/edit?usp=sharing)

**Comment by bedroesb** [comment]
@rabuono this should be fixed, can you check and than close the issue?

**Comment by rabuono** [comment]
Works for me!
Thanks!
