### ISSUE TITLE
Quality control - Human biomolecular data - Disease maps use case

### ISSUE THREAD

**Issue by EvaGarciaAlvarez** [elixir-europe/infectious-diseases-toolkit#98]
**What topic do you wish to add?**
Quality control measures for human biomolecular data. 

**To which existing Infectious Diseases Toolkit page should the topic be added to?**
Human biomolecular data > Quality control page

**Context**
Collect feedback from the disease map use case.

**Comment by lauportell** [comment]
This page is already in the IDTk
