### ISSUE TITLE
Quality control - Human clinical and health data

### ISSUE THREAD

**Issue by EvaGarciaAlvarez** [elixir-europe/infectious-diseases-toolkit#99]
**What topic do you wish to add?**
Quality control measures for human health and clinical data.

**To which existing Infectious Diseases Toolkit page should the topic be added to?**
Human clinical and health data > Quality control page

**Context**
Collect feedback from the baseline use case.

**Comment by bedroesb** [comment]
I will use this issue to collect all data related to Quality control. 


A working document related to this topic can be found here on [Google Docs](https://docs.google.com/document/d/16e5emhFVmS88bAAXo22A74m4ZlTgLbcc/edit)
